services:
  - type: web
    name: pce-clfs
    runtime: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: "file:./prod.db"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: PORT
        value: "5000"
